trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'
  displayName: 'Publish complete workspace into Azure Artificats'

